// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {devtoys} from '../models';

export function Base64Text(arg1:devtoys.Base64TextReq):Promise<devtoys.Base64TextRes>;

export function ConvertNumberBase(arg1:devtoys.NumberBaseConversionReq):Promise<devtoys.NumberBaseConversionRes>;

export function ConvertTextBinary(arg1:devtoys.TextBinaryConversionReq):Promise<devtoys.TextBinaryConversionRes>;

export function Escape(arg1:devtoys.EscapeReq):Promise<devtoys.EscapeRes>;

export function Hash(arg1:devtoys.HashReq):Promise<devtoys.HashRes>;

export function UnixTimestamp(arg1:devtoys.UnixTimestampReq):Promise<devtoys.UnixTimestampRes>;
