// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Text(arg1) {
  return window['go']['devtoys']['App']['Base64Text'](arg1);
}

export function ConvertNumberBase(arg1) {
  return window['go']['devtoys']['App']['ConvertNumberBase'](arg1);
}

export function ConvertTextBinary(arg1) {
  return window['go']['devtoys']['App']['ConvertTextBinary'](arg1);
}

export function Escape(arg1) {
  return window['go']['devtoys']['App']['Escape'](arg1);
}

export function Hash(arg1) {
  return window['go']['devtoys']['App']['Hash'](arg1);
}

export function UnixTimestamp(arg1) {
  return window['go']['devtoys']['App']['UnixTimestamp'](arg1);
}
