// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AES(arg1) {
  return window['go']['devtoys']['App']['AES'](arg1);
}

export function Base64Text(arg1) {
  return window['go']['devtoys']['App']['Base64Text'](arg1);
}

export function ConvertNumberBase(arg1) {
  return window['go']['devtoys']['App']['ConvertNumberBase'](arg1);
}

export function ConvertString(arg1) {
  return window['go']['devtoys']['App']['ConvertString'](arg1);
}

export function ConvertTextBinary(arg1) {
  return window['go']['devtoys']['App']['ConvertTextBinary'](arg1);
}

export function DoHttp(arg1) {
  return window['go']['devtoys']['App']['DoHttp'](arg1);
}

export function Escape(arg1) {
  return window['go']['devtoys']['App']['Escape'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['devtoys']['App']['GeneratePassword'](arg1);
}

export function GenerateSSHKey(arg1) {
  return window['go']['devtoys']['App']['GenerateSSHKey'](arg1);
}

export function GetSetting() {
  return window['go']['devtoys']['App']['GetSetting']();
}

export function Hash(arg1) {
  return window['go']['devtoys']['App']['Hash'](arg1);
}

export function SSLCertificate(arg1) {
  return window['go']['devtoys']['App']['SSLCertificate'](arg1);
}

export function SetSetting(arg1) {
  return window['go']['devtoys']['App']['SetSetting'](arg1);
}

export function UnixTimestamp(arg1) {
  return window['go']['devtoys']['App']['UnixTimestamp'](arg1);
}
