// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1, arg2, arg3) {
  return window['go']['apps']['Base64TextApp']['Base64Decode'](arg1, arg2, arg3);
}

export function Base64Encode(arg1, arg2, arg3) {
  return window['go']['apps']['Base64TextApp']['Base64Encode'](arg1, arg2, arg3);
}
